### ISSUE TITLE
DialogPanel.csのメソッドが他のクラスから実行されない

### ISSUE THREAD

**Issue by Kanjyosen** [rintech/Blueprint#5]
オブジェクト参照とDialogPanelの設定済。
VS2015でも特段エラーは表示されませんでした。
Unity側でエラーのような表示があったので掲載。
![capture](https://user-images.githubusercontent.com/15709828/36070891-2b547ca4-0f48-11e8-9deb-93db33e01dbb.PNG)
![capture2](https://user-images.githubusercontent.com/15709828/36070892-31b00adc-0f48-11e8-9576-17e2b1018b51.PNG)

**Comment by Densyakun** [comment]
修正しました

**Comment by Kanjyosen** [comment]
ありがとうございます。
正常な動作になりました。
